### PR TITLE
wip: add versionList() method to get list of versions

### PR DESCRIPTION
**Pull request by isaacs**
List is sorted in priority order.

Needs tests, do not land yet.

### CODE REVIEW

**Comment by ljharb** [comment]
Seems great!

**Comment by wraithgar** [comment]
Doesn't look like this ever got finished and afaict nobody is picking this up.

**Comment by isaacs** [comment]
😭 totally forgot why we even wanted this, I remember it seeming important at the time, though.

**Comment by wraithgar** [comment]
As per all the other PRs I have been dealing with but not able to rebase/land. We will happily work with folks who want to resubmit.

**Pull request closed without merging**
